### ISSUE TITLE
Did this get built?

### ISSUE THREAD

**Issue by jimlakey** [verbb/postie#1]
Hi Josh,

Does this project exist anywhere? This is exactly what I'm looking for and would love to see the code if it does exist. Thanks!

**Comment by keithmancuso** [comment]
+1 would love to help out if this is still something in development

**Comment by engram-design** [comment]
Plugin is in active development - will be releasing the beta soon!

**Comment by peter-tell** [comment]
Just curious if there's been any progress on this? Thanks!

**Comment by engram-design** [comment]
Sure did! Finally Postie is seeing the light of day - https://github.com/verbb/postie/releases/tag/1.0.0
