### ISSUE TITLE
Add order to modify rates event

### ISSUE THREAD

**Issue by keyurshah** [verbb/postie#10]
I was thinking of how to access the order information from a modify rates event. Would it be possible to include `$event->order` as an event property or is the `$order` info available in some other way?

```
Event::on(USPS::class, Provider::EVENT_MODIFY_RATES, function(ModifyRatesEvent $event) {
    $rates = $event->rates; // The calculated rates from Postie
    $response = $event->response; // The raw response from the provider's API

    // To modify the rates, directly modify the variable via `$event->rates = ...`

});
```

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/postie/releases/tag/2.1.0). Thanks @AugustMiller
