### ISSUE TITLE
vinceg/usps-php-api package is abandoned. Is it safe to use?

### ISSUE THREAD

**Issue by ggallo909** [verbb/postie#103]
### Question

Composer always warns that package vinceg/usps-php-api is abadoned:

> Package vinceg/usps-php-api is abandoned, you should avoid using it. No replacement was suggested.

Postie make use of the mentioned package. Is it safe to keep using it on production sites?

**Comment by engram-design** [comment]
It’s safe to continue using it on production for sure. Long-term we’ll need to find an alternative (haven’t found one yet), or build the integration on our own.

We’ll likely be doing the latter with a focus on a brand new PHP package that abstracts a lot of provider APIs https://github.com/verbb/postie/issues/79

**Comment by ggallo909** [comment]
Sweet, thanks for confirming.

> We’ll likely be doing the latter with a focus on a brand new PHP package that abstracts a lot of provider APIs https://github.com/verbb/postie/issues/79

A brand new package that abstracts to other provider APIs sounds great!

**Comment by engram-design** [comment]
Updated in [4.0.0](https://github.com/verbb/postie/releases/tag/4.0.0) thanks to [verbb/shippy](https://github.com/verbb/shippy)
