### ISSUE TITLE
UPS Oauth

### ISSUE THREAD

**Issue by thomasdefilippis** [verbb/postie#107]
### Describe the bug

Not sure whether this is a true bug, but ups just discontinued api access without oauth. So, likely this shipping method will need a rewrite.

We are under a time crunch to get this working for a customer who is launching in a month. Any chance that this feature could be high on the list since ups method seems to be unusable?

Thanks,
Thomas Defilippis

### Steps to reproduce

1. 
2. 

### Craft CMS version

4

### Plugin version

3.03

### Multi-site?

no

**Comment by engram-design** [comment]
It's a known issue, yep! Unfortunately, I can't seem to get a new app setup with UPS, and their support has been frustrating to deal with. If you're willing to setup a test app and send through credentials (just for testing, not production), I'd be happy to continue with the refactoring. You're welcome to get in touch via `support@verbb.io`.

We're also underway with some major rewrites, and we're factoring in this change into that.

**Comment by thomasdefilippis** [comment]
Great,

thanks for the quick response.

The only problem with sending you credentials after creating an app is I would rather not share access to my account where a credit card  is attached. I could try creating an app and see if I run into any issues. What issues were you having with the process?


thanks,
Thomas Defilippis

**Comment by engram-design** [comment]
Yep, not suggesting sharing your UPS account details, just the `clientId` and `clientSecret` of the app you'd [create](https://developer.ups.com/apps). But I do see what you mean that a credit card is attached to that which would be understandably problematic.

It's more on the last step of the process, we get the following error

<img width="1429" alt="image" src="https://github.com/verbb/postie/assets/1221575/62635d0e-c38a-43f3-9fd5-88d16b3fa934">

And UPS support have just come back to us multiple times saying "it's fixed", but it doesn't work. I'm wondering if maybe it's our credit card being Australian, as all other details are pretty basic.

Still working on it!

**Comment by thomasdefilippis** [comment]
Alright, I tried signing up for a new account, and I got the same screen
![Screenshot 2023-07-27 at 7 57 21 AM](https://github.com/verbb/postie/assets/61485862/7d3fd395-c245-4dbb-8e39-4bb1f08513ab)

So, I don't think it is the fact that you have Australian credit card. Also, I know it is the UPS (so they like addresses), but they had me fill out around 4-5 address fields before it errored out. The image below pretty much sums up their process:
![Screenshot 2023-07-27 at 7 52 05 AM](https://github.com/verbb/postie/assets/61485862/de19e3d2-0d27-4b5f-8aaf-f5761a320aae)


going to submit a ticket to them as well.

**Comment by thomasdefilippis** [comment]
Any news on this issue. Want to know if I need to go custom on my own for the ups stuff.

**Comment by engram-design** [comment]
Actively working on it. Have just started the process to gain a shipping account with UPS, and they're finalising setting it up. All going well, I should have some testing details to be able to create an app and test this.

Did you ever get a response back from yourself being unable to create an app?

**Comment by thomasdefilippis** [comment]
No unfortunately, every-time I try to create business account it fails with the same message. Are they doing a manual process for you?

**Comment by engram-design** [comment]
Yeah same on my end. Literally had to call and speak with a rep. Probably won’t get any further action until next week

**Comment by thomasdefilippis** [comment]
Cool, yeah, I think we are all in the same circumstance. Appreciate your work and look forward to the new release. Any estimation on that release. Are we looking at 3 weeks away or 2 months? Just want to figure out if I should start working on manual setup for ups until this is fixed.

**Comment by engram-design** [comment]
I would estimate a week or two!

**Comment by engram-design** [comment]
Added in [3.1.0](https://github.com/verbb/postie/releases/tag/3.1.0)

**Comment by thomasdefilippis** [comment]
Great, 

I just got api access from ups, so I think they figured something out over there on there end. Thanks for the quick release!

**Comment by thomasdefilippis** [comment]
Hey one last question:

I noticed that the daily pickup rates for ups were removed in the new version of the plugin?

Was that intentional?
