### ISSUE TITLE
Ups Daily Pickup Rate

### ISSUE THREAD

**Issue by thomasdefilippis** [verbb/postie#109]
### Question

I noticed that the daily pickup rates for ups not added to non-legacy ups connection in the new version of the plugin. Was that intentional? just trying to determine how to factor this into my client's rates.

Thanks for your help,
Thomas Defilippis

**Comment by engram-design** [comment]
Fixed in [3.1.1](https://github.com/verbb/postie/releases/tag/3.1.1)
