### ISSUE TITLE
Add events for beforeFetchRates

### ISSUE THREAD

**Issue by engram-design** [verbb/postie#11]
Allows modification of the API call to providers, before the call is made.

**Comment by siebird** [comment]
I could use this hook on a current project. In this case, it's shipping from multiple locations so being able to dynamically set the shipping location would be great.

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/postie/releases/tag/2.1.0), see [docs](https://verbb.io/craft-plugins/postie/docs/developers/events)

**Comment by siebird** [comment]
Thanks for getting this added Josh!
