### ISSUE TITLE
PHP warning after updating to 3.1.1

### ISSUE THREAD

**Issue by peteeveleigh** [verbb/postie#110]
### Describe the bug

After updating to 3.1.1 we now get an Exception thrown because of a PHP Warning.

`Undefined array key "boxSizes"`

The error is being thrown in line 241 of  /var/www/html/vendor/verbb/postie/src/base/Provider.php

### Steps to reproduce

1. Update to 3.1.1
2. Visit Site homepage or Postie settings in CP

### Craft CMS version

4.1.17

### Plugin version

3.1.1

### Multi-site?

No

### Additional context

I've reverted back to 3.0.3 and seeing the same error. I wonder if it was just being masked by not running in dev mode.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/postie:"dev-craft-4 as 3.1.1"`.

**Comment by peteeveleigh** [comment]
Hey 
Thanks for this. I can confirm that it fixes the reported issue.

I'm seeing another issue though. Will raise a new ticket for it as it's related to guzzle
