### ISSUE TITLE
Set 'Shipping Category Conditions' for a service in postie.php file

### ISSUE THREAD

**Issue by sjcallender** [verbb/postie#115]
### Question

Is it possible to set the values for a service's 'Shipping Category Conditions' values in the config/postie.php file?

It appears not. Since we need specific rules, we're unable to use the `services` config at all as it sets each category condition to "Allow."

### Additional context

We have this our config/postie.php file...
```
                'services' => [
                    'S_AIR_1DAY' => 'UPS Next Day Air (Overnight)',
                    'S_AIR_2DAY' => 'UPS Second Day Air (in 2 Days)',
                    'S_3DAYSELECT' => 'UPS Three-Day Select (in 3 Days)',
                    'S_GROUND' => 'UPS Ground (1-5 Days)'
                ]
```

In the CP, the result is...

<img width="808" alt="Markup 2023-09-19 at 21 19 58" src="https://github.com/verbb/postie/assets/984311/94c41631-dfd2-4ea9-bee5-495be3362bb6">

...where we can't set a condition to "Disallow."

We have to remove the `services` config in order to achieve the following...

<img width="763" alt="Markup 2023-09-19 at 21 22 08" src="https://github.com/verbb/postie/assets/984311/d0669623-0c92-469a-853a-1578daa7e968">

We'd like to be able to define all this in the config file if possible.

**Comment by engram-design** [comment]
You can if you like! You just need to alter your syntax.

```php
'services' => [
    'S_GROUND' => [
        'enabled' => true,
        'name' => 'UPS Ground (1-5 Days)',
        'shippingCategories' => [
            1 => [
                'condition' => 'disallow',
            ],
        ],
    ],
],
```

Note that the array index `1` in this case refers to your Shipping Category ID, not just the array index.
