### ISSUE TITLE
Add USPS Ground Advantage

### ISSUE THREAD

**Issue by RitterKnightCreative** [verbb/postie#117]
### What are you trying to do?

My client was asking about a USPS service called Ground Advantage. 

Did a quick little research on USPS Ground Advantage service and it looks like it [replaces](https://www.pitneybowes.com/us/blog/what-is-usps-ground-advantage.html) a couple older USPS services, most notably First Class Package Service and renames the lot to Ground Advantage.  

It looks like Postie supports at least one or two of the (old) abovementioned services so theoretically it should support Ground Advantage? Could be just a rename of one of the existing services?

### What's your proposed solution?

Update the plugin with updated service names.

**Comment by engram-design** [comment]
I'll take a look into this, we've got a pretty big refactor on the horizon for Postie, including updating the USPS API. I'll do a bit of research into it!

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/postie:"dev-craft-4 as 3.1.7"`.

**Comment by engram-design** [comment]
Updated in [4.0.0](https://github.com/verbb/postie/releases/tag/4.0.0)
