### ISSUE TITLE
`Order::setEmail()` has been deprecated

### ISSUE THREAD

**Issue by bennonite** [verbb/postie#131]
### Describe the bug

I have a fresh install of Postie with a UPS provider created and creds entered. I'm trying out the Rates Testing tab with the default addresses left as is. Clicking the test rate button returns `Order::setEmail() has been deprecated use Order::setCustomer()` instead. 

![test rates](https://github.com/verbb/postie/assets/62555046/b6fc8ced-a03a-41f0-bc36-77a2ff974551)

### Steps to reproduce

1. Install a provider 
2. Go to Rates Testing
3. Click "Test Rates" button

### Craft CMS version

4.5

### Plugin version

4.0.2

**Comment by engram-design** [comment]
As it's a deprecation warning you must have it [enabled](https://craftcms.com/knowledge-base/preparing-for-craft-4#fix-deprecation-warnings) to throw an error for a warning?

Fixed for the next release. To get this early, run `composer require verbb/postie:"dev-craft-4 as 4.0.2"`.

**Comment by bennonite** [comment]
Ah you're right, that was it. Thank you!
