### ISSUE TITLE
NZ Post authentication error

### ISSUE THREAD

**Issue by krisMoca** [verbb/postie#135]
### Describe the bug

I have a correct client id and client secret as I can login via website of nz post.

When I used the plugin it's throwing an error. I wonder if the endpoint is wrong?
![image](https://github.com/user-attachments/assets/aae5e65f-ce99-4dc3-aa28-9bbcebf411e6)

I can login via website
![image](https://github.com/user-attachments/assets/168ef9ab-8e7a-46db-82e8-e1f7a255ae51)

### Steps to reproduce

1. Login to CP
2. Create a new provider. Postie > Providers > New Provider
3. Enter Client ID and Client secret
4. Test rates

### Craft CMS version

5.10.0

### Plugin version

"verbb/postie": "dev-craft-4 as 4.0.3"

### Multi-site?

Yes

**Comment by engram-design** [comment]
According to their [docs](https://anypoint.mulesoft.com/exchange/portals/nz-post-group/b8271f09-2ad8-4e1c-b6b1-322c5727d148/parceladdress-api/minor/1.0/pages/Authentication/) `oauth.nzpost.co.nz` is correct.

I see in the debug output that the client secret is `NZ_POST_CLIENT_SECRET` - I just wanted to check if that's something you've just swapped in for the sake of posting here, or if that's an incorrect reference to an `.env` variable?

**Comment by krisMoca** [comment]
Hi I used env variables to to set the client id and secret, and the references were correct.

When I set it up directly and clicked on "Test Rates" I've got a different error.
![image](https://github.com/user-attachments/assets/049de4f4-e93c-4071-aecf-2443ea297f7c)

**Comment by engram-design** [comment]
Looks like the error response is being truncated, which I've updated for the next release. To get this early, run `composer require verbb/postie:"dev-craft-4 as 4.0.4"`. If you could try that, I'd be interested what the full error message here is.

In addition, would it be possible to gain your client ID/Secret (privately) for testing? I have an existing client that's working on my end, so I just wanted to ensure it's nothing to do with your client. If you're able to, send to `support@verbb.io`.

**Comment by engram-design** [comment]
Fixed in [4.0.5](https://github.com/verbb/postie/releases/tag/4.0.5)
