### ISSUE TITLE
FedEx Freight Cannot Use Account

### ISSUE THREAD

**Issue by apitel** [verbb/postie#136]
### Describe the bug

When trying to retrieve rates from carts/orders/plugins rate testing with FedEx Freight provider it throws an error that billing information is not set upon rate retrieval despite billing address being added to the settings.

### Steps to reproduce

![CleanShot 2024-07-24 at 05 44 54@2x](https://github.com/user-attachments/assets/4bde6555-dae5-4a98-8445-b52debf21b76)

![CleanShot 2024-07-24 at 05 45 32@2x](https://github.com/user-attachments/assets/52cff650-6dbc-4edb-9381-31265d31ba0b)

Testing with default set-up and bumping up dimensions and weight to freight legitimate amounts:
![CleanShot 2024-07-24 at 05 46 27@2x](https://github.com/user-attachments/assets/c21acab8-a385-4591-b253-ae9142139a7a)

An identical issue is seen in carts/orders/testing rates when recalculating:
![CleanShot 2024-07-24 at 05 47 53@2x](https://github.com/user-attachments/assets/079b7213-5cf0-4dea-a318-2428216ef4d7)

Parameter $billing for verbb/shippy/src/carriers/FedExFreight.php still needs to be set and is called to retrieve test rates:
![CleanShot 2024-07-24 at 05 48 21@2x](https://github.com/user-attachments/assets/293ba2a6-5bc4-4300-bea1-20f36d0a8314)

verbb/shippy/src/carriers/FedExFreight.php settings do have valid billing information which is not used to set $billing:
![CleanShot 2024-07-24 at 05 48 49@2x](https://github.com/user-attachments/assets/b021a1ce-3048-4c49-bc74-fdca71b4c33a)

### Craft CMS version

5.2.8

### Plugin version

5.0.2

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/postie:"dev-craft-5 as 5.0.2"`.

**Comment by apitel** [comment]
I tried the suggested method of unblocking us: composer require verbb/postie:"dev-craft-5 as 5.0.2" but it unfortunately throws a composer error:

![image](https://github.com/user-attachments/assets/6af758f8-0df7-4766-973b-d7770cf6402b)


    - Root composer.json requires verbb/postie dev-craft-5 as 5.0.2 -> satisfiable by verbb/postie[dev-craft-5].
    - verbb/postie dev-craft-5 requires verbb/shippy ^1.0.4 -> found verbb/shippy[dev-main, 1.0.0, 1.0.1, 1.0.2, 1.0.3] but it does not match the constraint.

**Comment by engram-design** [comment]
Ah, apologies - I forgot to tag a proper release for `verbb/shippy` - that command should work now.

**Comment by engram-design** [comment]
Fixed in [5.0.3](https://github.com/verbb/postie/releases/tag/5.0.3)
