### ISSUE TITLE
Postie Sending Incorrect Quantity of Packages to FedEx API

### ISSUE THREAD

**Issue by apitel** [verbb/postie#138]
### Describe the bug

Postie is sending multiple packages to the API to retrieve pricing when multiple providers are enabled; in this case FedEx and FedEx Freight. When disabling one of the two providers, Postie sends the correct amount of packages.

This seems to be the place where it is happening: `vendor/verbb/postie/src/services/Service.php:91`

<img width="1512" alt="image-20240814-104050" src="https://github.com/user-attachments/assets/4d273900-11a3-45ce-8135-af7a45adc5fd">

### Steps to reproduce

1. Enable multiple FedEx providers
2. Send over shipping price request

### Craft CMS version

5.3

### Plugin version

5.0.4

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/postie:"dev-craft-5 as 5.0.4"`.

**Comment by engram-design** [comment]
Fixed in [5.0.5](https://github.com/verbb/postie/releases/tag/5.0.5)
