### ISSUE TITLE
When using multiple providers, only first provider's results are displayed

### ISSUE THREAD

**Issue by keyurshah** [verbb/postie#14]
### Description
It seems that when I configure multiple providers, it only displays the shipping methods for the first enabled Provider on the cart page.

In my case I was configuring USPS and FedEx.

### Steps to reproduce

1. Add and configure 2 or more providers
2. Enable providers
3. Go to cart page and view shipping options
4. Options displayed are for the first enabled provider

### Additional info

- Plugin version: 2.0.8
- Craft version: 2.1.11

my postie config file is as follows:

```
return [
	'*' => [
			'pluginName' => 'Postie',
			'hasCpSection' => false,
			'enableCaching' => false,
			'displayDebug' => false,
			'displayErrors' => false,
	]
];
```

Thanks!

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/postie/releases/tag/2.1.0).
