### ISSUE TITLE
Cart without email throws error

### ISSUE THREAD

**Issue by maccadesign** [verbb/postie#144]
### Describe the bug

verbb\shippy\models\Address::setEmail(): Argument #1 ($email) must be of type string, null given when calling get-cart.

### Steps to reproduce

1. Add product to basket
2. Set a delivery address
3. Attempt to fetch the cart via `/actions/commerce/cart/get-cart`

### Craft CMS version

4.12.5

### Plugin version

4.0.7

### Multi-site?

No

### Additional context

The checkout is a single page checkout, so the user can fill in the address before the email which causes the issue.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/postie:"dev-craft-4 as 4.0.7"`.

**Comment by engram-design** [comment]
Fixed in [4.0.8](https://github.com/verbb/postie/releases/tag/4.0.8)

**Comment by maccadesign** [comment]
Thanks!
