### ISSUE TITLE
Vote for your provider

### ISSUE THREAD

**Issue by engram-design** [verbb/postie#2]
We'd love to support as many providers as we can, so lets start a vote! 

The rules are, add the name of the provider you want Postie to support *unless someone else has added it*. If they have, use the 👍 to upvote that provider. We'll prioritise providers based on votes.

**Comment by engram-design** [comment]
TNT Global

**Comment by engram-design** [comment]
<s>DHL Express</s> - Added!

**Comment by mdunbavan** [comment]
Royal Mail

**Comment by andrewjmyers** [comment]
<s>UPS</s> - Added!

**Comment by engram-design** [comment]
@andrewjmyers We ran into some issue with UPS when trying to test, apparently its a bit tricky to create a test account! Would you be willing to help out with any test details? Happy to touch base via Slack as well (@crawf).

**Comment by andrewjmyers** [comment]
@engram-design absolutely! I'll reach out on slack.

**Comment by maxwellhibbert** [comment]
StarTrack

**Comment by gjhead** [comment]
<s>UPS!</s> - Added!

**Comment by engram-design** [comment]
@mdunbavan If you're able to provide some API details for Royal Mail, we can look at getting it supported. Use https://verbb.io/craft-plugins/postie/support to get in touch.

@maxwellhibbert If you're able to provide some API details for Startrack, we can look at getting it supported. Use https://verbb.io/craft-plugins/postie/support to get in touch.

@andrewjmyers @gjhead UPS is now supported!

**Comment by engram-design** [comment]
Bring (https://developer.bring.com/)

**Comment by engram-design** [comment]
Postnord (https://developer.postnord.com/)

**Comment by chadcrowell** [comment]
Golden State Overnight

**Comment by dwhoban** [comment]
NZ Post https://www.nzpost.co.nz/business/developer-centre

**Comment by yoannisj** [comment]
Collissimo / Chronopost

**Comment by yoannisj** [comment]
Bpost

**Comment by swordinthestone** [comment]
Sendle for Australia https://www.sendle.com/

**Comment by engram-design** [comment]
@chadcrowell I'm struggling to get some API details (or docs) for Golden State Overnight. Do you have any info on your end?

@yoannisj I'm struggling to get some API details for Bpost. Do you have any info on your end?

**Comment by chadcrowell** [comment]
Thanks Josh- I have never found any public docs for GSO. My client doesn’t use them any longer so 🤷🏼‍♂️

Chad

**Comment by engram-design** [comment]
@chadcrowell Consider that in the too-hard basket for now!

**Comment by engram-design** [comment]
I'll be closing this thread now. Any future requests for provider, just open up a new issue.

Note that Bring, Sendle, NZ Post, Royal Mail and Colissimo have all been added in  [2.4.0](https://github.com/verbb/postie/releases/tag/2.4.0).
