### ISSUE TITLE
Add provider name to OrderAdjustment in Cart

### ISSUE THREAD

**Issue by alexgilbertDG** [verbb/postie#21]
I would like to show the provider name inside my order review twig template. 

Inside your 
```verbb\postie\models\ShippingRule.php```, adding a getDescription function that return 
```
return $this->provider->name . ' - ' . $this->shippingMethod->getName();
```
work for me but I can't modify the vendor folder.

I understand not everyone want that, so maybe you could call an event to change the name if we want inside our Craft module.

Something like that inside the getDescription function:
```
$description = parent::getDescription();

        $changeDescriptionEvent = new ChangeShippingRuleDescription([
            'description' => $description,
            'provider' => $this->provider,
            'shippingMethod' => $this->shippingMethod,
        ]);

        if (!$this->hasEventHandlers(self::EVENT_CHANGE_SHIPPING_RULE_DESCRIPTION)) {
            return $description;
        }

        $this->trigger(self::EVENT_CHANGE_SHIPPING_RULE_DESCRIPTION, $changeDescriptionEvent);

        return $description;
```
*Not working code, just example*

Thanks

**Comment by engram-design** [comment]
Added in [2.1.1](https://github.com/verbb/postie/releases/tag/2.1.1). See [docs](https://verbb.io/craft-plugins/postie/docs/developers/events#the-modifyShippingRule-event)
