### ISSUE TITLE
Postie failing to calculate multiple box sizes for FedEx

### ISSUE THREAD

**Issue by britteninc** [verbb/postie#24]
### Description
Postie's documentation states that "Postie creates only one box to fit all line items into" which creates a problem when I have multiple items that a user is adding to their cart, specifically when the quantities of these items are more than one.

Specific case: I have one product with dimensions of 9" x 15.5" x 4" and a weight of 7lbs. If I add one to my cart, FedEx returns a shipping calculation. If I increase the quantity to 25 then I receive the following error from FedEx: 

`[-][1][-][error][postie] FedEx: Rate Error: There are no valid services available.`

Seems like it should be able to calculate shipping for multiple boxes.

Another specific case: I have another product with dimensions of 21" x 11" x 14" with a weight of 4.38lbs. Adding one item to my cart and checking out produces the same error as above. Seems like there should be configuration settings to create custom box sizes like in WooCommerce.

### Steps to reproduce

1. Add an item to cart with dimensions and weights as listed above with high quantities.
2. Try to get FedEx to return rates.

### Additional info

- Plugin version: 2.1.1
- Craft version: Craft Pro 3.4.6

**Comment by engram-design** [comment]
Yep, so there's no support for multi-boxes (yet) in Postie, but its been high on the list for a while now to support that. It'll work pretty similar to WooCommerce I believe.

I'll keep you posted!

**Comment by siebird** [comment]
Yep–we're running into the same issue. Bundling all line items into one big box.

**Comment by engram-design** [comment]
A new box-packing algorithm has been added in [2.4.0](https://github.com/verbb/postie/releases/tag/2.4.0) which should improve this.
