### ISSUE TITLE
Unable to disable shipping rate per category

### ISSUE THREAD

**Issue by BrandonJamesBorders** [verbb/postie#31]
### Description
An individual shipping method is not saving shipping category conditions preference. 

### Steps to reproduce

1. Go to enabled shipping method (for example, UPS Ground)
2. Under shipping, category conditions update any category to anything other than allowed. (In this instance I have three shipping categories). 
3. Hit save, the page reloads and all categories remain as active.

### Additional info
I've tried this with using project config and not using project config. 

- Plugin version: 2.2.0
- Craft version: 3.4.18

**Comment by engram-design** [comment]
Fixed in [2.2.1](https://github.com/verbb/postie/releases/tag/2.2.1)
