### ISSUE TITLE
SurePost rating error causes other shipping methods to fail to be rated

### ISSUE THREAD

**Issue by Mosnar** [verbb/postie#34]
### Description
Because SurePost fetches its rate independently, it's possible for an exception to be thrown and break rate-fetching. SurePost has smaller allowed shipping dimensions than other shipping methods and when this limitation is hit, an InvalidResponseException is thrown.

Fixed in #33 

### Steps to reproduce

1. Have a large product (greater than 90" in one dimension)
2. Have 2 shipping methods enabled (UPS Ground & UPS SurePost)
3. Attempt to checkout - UPS Ground should be valid, SurePost should not be.
4. See that no shipping methods are returned.

### Additional info

- Plugin version: 2.2.3
- Craft version: 3.4.22.1

**Comment by engram-design** [comment]
Fixed in [2.2.4](https://github.com/verbb/postie/releases/tag/2.2.4), thanks!
