### ISSUE TITLE
In UPS Provider, if services defined in settings, and S_SURE_POST not enabled, undefined index error

### ISSUE THREAD

**Issue by GaryReckard** [verbb/postie#35]
I am defining the UPS services that are enabled in my `postie.php` config. I am not enabling S_SURE_POST, so that is not included in my list of services.

I am getting an undefined index error at https://github.com/verbb/postie/blob/6689e598d064f2852dc3f9194b2aa01b790db52f/src/providers/UPS.php#L272

I think this just needs an `isset` check first.

**Comment by rsanchez** [comment]
Same issue here.

**Comment by zachisit** [comment]
Same issue on my end. Seeking help!

**Comment by GaryReckard** [comment]
I found a temporary workaround, using this undocumented feature of providing an array for the provider services rather than just a string name, in `postie.php` config. So, adding this to my config:

``
'S_SURE_POST' => [
   'name' => 'Sure Post',
   'enabled' => false,
],
``

gets around the bug.

(the ability to provide both name and enabled status in an array in config should be mentioned on https://verbb.io/craft-plugins/postie/docs/get-started/configuration)

**Comment by santiDotIO** [comment]
Running into the same issue

**Comment by engram-design** [comment]
Sorry all, fixed in [2.2.5](https://github.com/verbb/postie/releases/tag/2.2.5)
