### ISSUE TITLE
Default template for displaying rates uses deprecated method for Commerce 3

### ISSUE THREAD

**Issue by sparkalow** [verbb/postie#36]
### Description
The [default template](https://verbb.io/craft-plugins/postie/docs/setup-configuration/displaying-rates) for displaying rates uses a method that results in a deprecation warning.

The warning:

> Order::getAvailableShippingMethods() has been deprecated. Use Order::getAvailableShippingMethodOptions()

I'm my case switching to `cart.availableShippingMethodOptions`  from `cart.availableShippingMethods` works for showing methods in the loop, but prices do not come through.
`[craft\commerce\models\ShippingMethodOption:_price] => null`

### Steps to reproduce

1. Install Postie & Craft Commerce 3
2. Use default template markup
3. Observe shipping methods during checkout

### Additional info

- Plugin version:
- Craft version: 3.4.24
- Craft Commerce version : 3.19
- Shipping provider: UPS

**Comment by engram-design** [comment]
I’ve been working with Luke on this one, and I believe its a Commerce issue - now fixed in https://github.com/craftcms/commerce/issues/1532

**Comment by RitterKnightCreative** [comment]
@engram-design Looks like ``method.getShippingRules`` is returning a blank array? 

For example the transit time in FedEx is no longer available.

**Comment by engram-design** [comment]
@RitterKnightCreative Can you confirm what version of Commerce you're on?

**Comment by RitterKnightCreative** [comment]
Tested on latest, 3.2.3.

**Comment by RitterKnightCreative** [comment]
@engram-design Looks like this could be a  Commerce issue then?

**Comment by engram-design** [comment]
Sorry to leave you hanging, seems that's the case. I might make a new issue to give it some attention.

**Comment by RitterKnightCreative** [comment]
@engram-design I chimed in as well on the Commerce thread, looks ike  no update? Guess we''ll have to live with the deprecations for now using the old method, hopefully it sticks around...

**Comment by engram-design** [comment]
@RitterKnightCreative Yeah, sadly not looking good. I'll keep an eye on it all though...

**Comment by RitterKnightCreative** [comment]
@engram-design looks like nothing has changed thus far?

**Comment by engram-design** [comment]
@RitterKnightCreative Nothing new I'm afraid 🦗
