### ISSUE TITLE
2.2.6 Breaks UPS checkouts that do not include a country selection

### ISSUE THREAD

**Issue by Mosnar** [verbb/postie#37]
### Description
As part of our checkout process, we do not collect the country, as the store is restricted to the US. The latest update sends the country ISO to UPS; however, this results in an a PHP exception since the country is null.

https://github.com/verbb/postie/blob/e0ae7dca03c32219cdf2c5752d54293ca398cde6/src/providers/UPS.php#L236

```
2020-07-13 11:09:11 [-][-][-][error][postie] UPS: API error: `Trying to get property 'iso' of non-object:236`.
```

### Additional info

- Plugin version: 2.2.6
- Craft version: 3.4

**Comment by engram-design** [comment]
Sorry about that, should be fixed in [2.2.7](https://github.com/verbb/postie/releases/tag/2.2.7)
