### ISSUE TITLE
DestinationPostalCode is required when AcceptanceDateTime is populated.

### ISSUE THREAD

**Issue by GaryReckard** [verbb/postie#38]
I was using a Hong Kong address, with no postal code set, and got the following error from USPS api in my postie log:

```
{
  "Package": {
    "Error": {
      "Number": "-2147219041",
      "Source": ";IntlRateV2.ProcessRequest",
      "Description": "DestinationPostalCode is required when AcceptanceDateTime is populated.",
      "HelpFile": "",
      "HelpContext": ""
    },
    "@attributes": {
      "ID": "2"
    }
  }
}
```

Perhaps this:
https://github.com/verbb/postie/blob/f5a51beb4012a33e3746d74fb70fbd3311d2bc3f/src/providers/USPS.php#L229-L230

should be surrounded by a check for the zip code?
```
if($order->shippingAddress->zipCode) {
    $package->setField('AcceptanceDateTime', DateTimeHelper::toIso8601(time()));
    $package->setField('DestinationPostalCode', $order->shippingAddress->zipCode);
}
```

**Comment by engram-design** [comment]
Wasn't aware of this requirement, updated in [2.2.8](https://github.com/verbb/postie/releases/tag/2.2.8)

**Comment by GaryReckard** [comment]
Thanks, Josh!
