### ISSUE TITLE
Array to string error after updating to Craft 3.5 / Commerce 3.2.0.1

### ISSUE THREAD

**Issue by challahan** [verbb/postie#39]
When navigating to checkout to update or add a customer address with Postie enabled, I'm now getting an array to string conversion error.

### Steps to reproduce

1. Add product to cart
2. Click checkout
3. Add new address - receive error

Get array to string error for file /vendor/verbb/postie/src/base/Provider.php

Line 295: implode('.', $order->shippingAddress->toArray()),

### Additional info

- Plugin version: 2.2.9
- Craft version: 3.5.0

**Comment by swordinthestone** [comment]
I have same problem with Craft 3.5.0 with Commerce 3.2.1.

**Comment by challahan** [comment]
It would be great to get an update on this as it seems others are having the same issue. I had to just disable the plugin entirely for now. Thanks!

**Comment by engram-design** [comment]
Should be fixed in [2.3.0](https://github.com/verbb/postie/releases/tag/2.3.0)
