### ISSUE TITLE
TypeError Upon Selecting UPS Shipping Method in Checkout

### ISSUE THREAD

**Issue by bfopma** [verbb/postie#4]
### Description
During checkout, if I select an available UPS shipping method (e.g. Next Day Air Saver) and continue to the next step in the checkout process, the following error occurs:

> TypeError
> Return value of craft\commerce\models\ShippingRule::getDescription() must be of the type string, null returned

This appears to trace back to `verbb\postie\models\ShippingMethod`, potentially in the `getShippingRules()` function.

I attempted to do something like `$shippingRule->description = 'Test';` but encountered other errors far beyond my level of competence. :)

### Steps to reproduce

1. Enable UPS provider (not sure if this issue is specific to UPS)
2. Add one or more eligible products to cart
3. Select an available UPS shipping method
4. Proceed to next step in checkout

### Additional info

- Plugin version: 2.0.1
- Craft version: 3.1.20.1
- Commerce version: 2.1.2
- PHP version: 7.2.9
- Database driver & version: MySQL 5.6.10

**Comment by engram-design** [comment]
Fixed in [2.0.2](https://github.com/verbb/postie/releases/tag/2.0.2)
