### ISSUE TITLE
Maximum Shipping Weight - No Shipping Options Available

### ISSUE THREAD

**Issue by challahan** [verbb/postie#42]
**Description**
Whenever adding multiple products that total a maximum shipping weight of about 150lbs+, I receive no shipping options available. It looks like there are maximum shipping weights for FedEx, UPS, etc. that would cause this.

The UPS website for example says: Packages can be up to 150 lbs.

With that said, is there a workaround to get UPS to calculate products as separate packages rather than one large single item of 150lbs?

**Comment by engram-design** [comment]
Not at the moment sorry. Work has started on better box-packing handling, but then I wasn't aware of this maximum weight.

I've added better handling on maximum weights for Fedex/USPS/UPS in https://github.com/verbb/postie/commit/c544fa99e4c837397878e54c71b2776d10d455e6

**Comment by engram-design** [comment]
Added the above short-term fix in [2.3.1](https://github.com/verbb/postie/releases/tag/2.3.1)
