### ISSUE TITLE
[FR] Modify Variant Query at "admin/postie/settings#tab-products"

### ISSUE THREAD

**Issue by xhuang9** [verbb/postie#43]
**What are you trying to do?**
I am trying to modify the Variant Query on admin/postie/settings#tab-products. 
We actually not want to ship all the products using postie.

It would be nice, if we can modify the query.

**What's your proposed solution?**
Maybe at verbb/postie/src/templates/settings/_panes/products.html:30
```
{% for variant in craft.postie.getVariants() %}

```
Then possibly triggering an event with variable function, allow modification to variant query object.

**Comment by engram-design** [comment]
Added in [2.3.1](https://github.com/verbb/postie/releases/tag/2.3.1). See [docs](https://verbb.io/craft-plugins/postie/docs/developers/events#the-modifyVariantQuery-event)
