### ISSUE TITLE
Manual fetch rates not working with Manual Order

### ISSUE THREAD

**Issue by keyurshah** [verbb/postie#45]
**Description**
When the setting `"manualFetchRates"=true` is enabled, it is not possible to get see possible shipping methods or get live rates in the admin screen when trying to manually create a new order or adjust an order.

Is there a way to change the behavior when in the admin and this setting is enabled?

**Steps to reproduce**
1. change setting to `true` for `manualFetchRates`
2. go to admin, and create a new order
3. for shipping methods, it shows None

![image](https://user-images.githubusercontent.com/744385/94072030-c256f300-fda9-11ea-8652-fa33af44451e.png)

**Additional info**
- Plugin version:  2.3.0
- Craft version: Commerce 2.6.2
- Multi-site: No

Thanks.

**Comment by engram-design** [comment]
Added in [2.3.1](https://github.com/verbb/postie/releases/tag/2.3.1)
