### ISSUE TITLE
[FR] Adding Australia post postage/letter/domestic/calculate 

### ISSUE THREAD

**Issue by xhuang9** [verbb/postie#48]
**What are you trying to do?**
My client has a really light weighted product (Calendars) can be post by letter. The postage cost for letters was $4.8 using C4 size. Instead of the cheapest parcel, it would be costing $8. And they can fit 3 of the same item in that letter. So its 3 for $4.8, instead of 1 for $8. But they are fine with 1 for $4.8. 

Background:
I am currently doing the craft commerce shipping category + shipping methods to enable post via letter. Although there are only 4 types of regular letters sizes in Australia Post, but I had to do 8 shipping categories, because my client also required some products aren't available for pickup. 

**What's your proposed solution?**

Using API to check if the item can be shipped with letters, and get the estimate as well.
Domestic: https://digitalapi.auspost.com.au/postage/letter/domestic/service.json
International: https://digitalapi.auspost.com.au/postage/letter/international/service.json

By the way, the `height` of the API was the `thickness` of letters, and it can't be greater than 20 mm. 
So maybe do a pre-check for the `height`of each variant, if it's greater than 20 mm. We don't have to try to call letters API.

And letter postage option should be strictly limited to the items that are provided with dimensions. If the variant only provided weight, we can skip the domestic letter shipping.

**Comment by engram-design** [comment]
Added in [2.4.0](https://github.com/verbb/postie/releases/tag/2.4.0)
