### ISSUE TITLE
No shipping options available

### ISSUE THREAD

**Issue by roberthallatt** [verbb/postie#5]
### Description

I have configured the addon to use Canada Post shipping rates. While on the checkout page, I am presented with no shipping options. The only thing returned is this message "No shipping options available". I have followed the documentation closely and all my settings in the control panel are configured correctly.

The following details are documented in the plugin log file:

**Message before I confirm my address:**

2019-04-05 07:23:35 [-][28][-][error][postie] Canada Post: No shipping address for order.

**Message after I confirm my address:**

`<messages xmlns="http://www.canadapost.ca/ws/messages">
<message>
<code>Server</ (truncated...)
:113`.
2019-04-05 07:23:43 [-][28][-][error][postie] Canada Post: API error: `Client error: `POST https://ct.soa-gw.canadapost.ca/rs/ship/price` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>`

### Steps to reproduce

1. Add product to cart
2. Navigate to checkout page and login
3. Confirm my address
4. At this point, the "No shipping options available" message appears

### Additional info

- Plugin version: 2.0.1 (in trial mode)
- Craft version: 3.1.21.1

**Comment by moyger** [comment]
Same with me. Is there some sort of Estimate or Calculation on the checkout process. There's also no provided template in the shipping method. How can we display how much is the shipping cost?

**Comment by BrandonJamesBorders** [comment]
@roberthallatt @moyger Have either of you figured this out?

**Comment by engram-design** [comment]
So firstly the `[error][postie] Canada Post: No shipping address for order.` message was incorrectly stated as an error - it really isn't at this stage. The latest version has changed this to a log event.

So sorry for the delayed response, and I'd likely need more information about the 500 error. Do you have `displayErrors` [config setting](https://verbb.io/craft-plugins/postie/docs/get-started/configuration) turned on? Or do you have more information in the log file? Happy to chat further on Discord (handle `crawf`), even though this is a bit of an old issue. 

@moyger There's no templating you need to do. Shipping methods will no longer appear in the control panel like they did in Commerce v1 as well (which is a bit annoying).

**Comment by roberthallatt** [comment]
Hi Josh,

The plugin is great but is there anyway that I can get a postage rate using the customers address as the source instead of the default that you enter in Craft Commerce? I know it seems like a strange way of doing it but apparently that is what we do here at CPS. So, for example, if you live in the province of Quebec, the shipping rate is calculated and the customer will need to pay the Quebec tax rate. Currently, the shipping rate returned uses the Ontario tax rate in its calculation because that is where our office is based. It doesn’t matter that we onlyget charged the Ontario tax rate.

Let me know if you have any ideas on how we might do this.

Thanks,

Rob

On May 31, 2019, at 10:47 PM, Josh Crawford <notifications@github.com<mailto:notifications@github.com>> wrote:


So firstly the [error][postie] Canada Post: No shipping address for order. message was incorrectly stated as an error - it really isn't at this stage. The latest version has changed this to a log event.

So sorry for the delayed response, and I'd likely need more information about the 500 error. Do you have displayErrors config setting<https://verbb.io/craft-plugins/postie/docs/get-started/configuration> turned on? Or do you have more information in the log file? Happy to chat further on Discord (handle crawf), even though this is a bit of an old issue.

@moyger<https://github.com/moyger> There's no templating you need to do. Shipping methods will no longer appear in the control panel like they did in Commerce v1 as well (which is a bit annoying).

**Comment by engram-design** [comment]
@roberthallatt Does seem like an interesting request. Will that work? The source and destination address would be the same?

I've added a new event in [2.1.0](https://github.com/verbb/postie/releases/tag/2.1.0) to modify the store value, which might help in this instance, see [docs](https://verbb.io/craft-plugins/postie/docs/developers/events), that should work?

**Comment by engram-design** [comment]
Closing due to age
