### ISSUE TITLE
No shipping options for product quantities greater than 10

### ISSUE THREAD

**Issue by challahan** [verbb/postie#50]
**Description**
I'm not sure when this first started occurring, but I'm noticing an issue in my store where any products added to the cart with a quantity greater than 10 do not show any shipping options. If I change it to 9, the shipping options populate fine. This is the same across all products, regardless or price or weight.

**Steps to reproduce**
1. Add product to cart
2. Change quantity to 10
3. No shipping options available (using FedEx and UPS only)

<img width="1287" alt="Screen Shot 2020-11-17 at 2 44 55 PM" src="https://user-images.githubusercontent.com/5162069/99439954-e20b2300-28e3-11eb-8e61-929e95fa04f1.png">

**Additional info**
- Plugin version: 2.3.5
- Craft version:  3.5.15.1
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
It would certainly be coming down to the combined dimensions, not necessarily weight. For instance, an example product with x20 in the cart (for Fedex):

![Screen Shot 2020-11-18 at 3 37 41 pm](https://user-images.githubusercontent.com/1221575/99484217-033b4480-29b4-11eb-8963-f059eee304c3.png)

But the product is 100mm x 100mm x 100mm and 100g, so it'll easily fit in most instances. Even if we go over a weight limit (150lb), it'll just split them into additional boxes. I'd say it comes down to dimensions, which need improving with a box packing algorithm.

**Comment by challahan** [comment]
You're right - I've reduced the dimensions on the test product and it does allow me to add more than 10, with shipping still being calculated. Appears they are not being split into separate boxes based on dimensions, just weight.

I found the following for FedEx and UPS - not sure if it's helpful:

UPS:
* Packages can be up to 165 inches in length and girth combined.
* Packages can be up to 108 inches in length.

FedEx:
With FedEx Express® U.S. services, up to 119" in length and 165" in length and girth.
• With FedEx Express international services, up to 108" in length and 130" in length and girth.
• With FedEx Express® Freight Services, Skids exceeding 2,200 lbs. in weight or exceeding 70" in height, 119" in length, or 80" in width require prior approval. FedEx Freight® shipments may be palletized or nonpalletized, weigh up to 20,000 lbs., and measure up to 21 feet in length.
• With FedEx Ground® and FedEx Home Delivery® Services, you can ship packages up to 150 lbs; up to 108" in length, and 165" in length plus girth.

**Comment by engram-design** [comment]
Thanks for that info! I'm in the middle of new box-packing changes, and this may or may not already take care of this scenario, but I'll ensure this is taken into account.

**Comment by engram-design** [comment]
A new box-packing algorithm has been added in [2.4.0](https://github.com/verbb/postie/releases/tag/2.4.0) which should improve this.
