### ISSUE TITLE
Freight Shipping

### ISSUE THREAD

**Issue by challahan** [verbb/postie#53]
**Description**
Can you tell me under what conditions the freight shipping (for FedEx) should be triggered? 

It looks like the shipment must be greater than 150lbs for FedEx Freight. I've added some products over that amount to the cart and enabled FEDEX_FREIGHT_ECONOMY and FEDEX_FREIGHT_PRIORITY, but still don't see those displayed as shipping options.  

Note - I have pack into boxes selected.

**Additional info**
- Plugin version: 2.4.2
- Craft version: 3.5.16

**Comment by engram-design** [comment]
After a little bit of research, it looks like we need to supply a specific "Freight" account number, in addition to the regular details. FedEx has two different accounts: one for express (ground / parcel / etc) and one for freight (LTL, freight economy, etc).

Would you be willing to assist with testing this functionality? I would need your "FedEx Freight Account Number" to test on my end, as there is a little bit of extra work involved. Feel free to reach out privately (Craft Discord `crawf` or email `support@verbb.io`

Until then, looks like freight services with FedEx are unsupported.

**Comment by engram-design** [comment]
Added in [2.4.5](https://github.com/verbb/postie/releases/tag/2.4.5)

**Comment by mufi-siebird** [comment]
Hey! Anyone knows how to get this `"Freight" account number`?

**Comment by engram-design** [comment]
@mufi-siebird Your client should have this when they created their Fedex account. I wasn't able to get one for testing purposes, so you'll need a real Fedex account with freight service support.
