### ISSUE TITLE
[FR] Support for labels and tracking for DPD

### ISSUE THREAD

**Issue by bartrylant** [verbb/postie#55]
Seeing the upcoming support for tracking and printing labels, it would be cool if there was support for DPD. They have a full working api on github. DPD is affiliated to Colissimo (which is currently supported), so they might use roughly the same setup.

**Comment by roelvanhintum** [comment]
@bartrylant, is "upcoming support for tracking and printing labels" regarding the Postie plugin or DPD? This would be nice for all providers.

**Comment by bartrylant** [comment]
The Postie plugin. I've read it on the Postie website. No mention of DPD so far :-(

**Comment by engram-design** [comment]
As far as I can tell, DPD don't seem to support rates through their API, much like Colissimo.

As for labels and tracking, that's still coming, as there's a lot to consider.

**Comment by richardcalahan** [comment]
Curious if there's an ETA on the shipping labels integration? Would be a game changer

**Comment by ax2000** [comment]
Also curious if there's an ETA for the labels

**Comment by engram-design** [comment]
Labels and tracking will be available in the next few months.

@bartrylant Back to your original question, I can't seem to register for API access of DPD, and there also seems to be region-specific services if I'm not mistaken? So firstly, what region are you after, and secondly would you be willing to assist with API access?

**Comment by engram-design** [comment]
Labels and tracking has now been added in [4.0.0](https://github.com/verbb/postie/releases/tag/4.0.0). I don't believe DPD support an API, so closing for now.
