### ISSUE TITLE
FedEx: Rate Error: There are no valid services available

### ISSUE THREAD

**Issue by Stalex89** [verbb/postie#58]
**Description**
I'm using headless Craft CMS 3 for backend + Nuxt.js as frontend.
I want to add FedEx shipping option for the website. 
Currently I'm using FedEx test account for development.
The problem is that I see no Fedex shipping methods/rates on the frontend.

Shipping country: The Netherlands

When I'm trying to get cart response in Postman, I see the following:
<img width="864" alt="Screenshot 2021-02-18 at 10 56 59" src="https://user-images.githubusercontent.com/23526237/108344537-8a7b9c80-71dd-11eb-8b20-112f5d0ab8b5.png">

I follower the documentation and I think I've configured everything. Can you please tell me if I have something extra to configure?

Thank you!

**Steps to reproduce**
1. Install Postire plugin
2. Configure Postie (enable debug and error display)
3. Create a product
4. Add product to cart
5. Call '/?action=commerce/cart/get-cart&note=from+ajax' from Postman

**Additional info**
- Plugin version: 2.4.6 Trial
- Craft version: Craft Pro 3.5.17.1
- Multi-site: No

**Additional context**
My configuration:
![Screenshot 2021-02-18 at 11 43 23](https://user-images.githubusercontent.com/23526237/108345795-f7436680-71de-11eb-8ed8-71eca6110d43.png)
![Screenshot 2021-02-18 at 11 45 02](https://user-images.githubusercontent.com/23526237/108345861-0a563680-71df-11eb-9330-f6b879d06e7c.png)
![Screenshot 2021-02-18 at 11 45 53](https://user-images.githubusercontent.com/23526237/108345899-12ae7180-71df-11eb-9196-0d10fa9bf4ba.png)
![Screenshot 2021-02-18 at 11 46 10](https://user-images.githubusercontent.com/23526237/108345929-1b9f4300-71df-11eb-8331-82eea96d48ee.png)
![Screenshot 2021-02-18 at 11 49 06](https://user-images.githubusercontent.com/23526237/108346180-69b44680-71df-11eb-9ffe-67b7bb940e29.png)
![Screenshot 2021-02-18 at 11 50 49](https://user-images.githubusercontent.com/23526237/108346434-a718d400-71df-11eb-84ab-a29431c1dc57.png)

**Comment by engram-design** [comment]
Looks like everything is setup correctly. Can you consult the storage/logs/postie.log file?

What test credentials are you using? I know sometimes this can be finicky depending on the country of origin your FedEx account is created on.

What origin and destination addresses are you testing with?

**Comment by Stalex89** [comment]
@engram-design Thank you for the quick response, here are the latest items from the storage/logs/postie.log: 
```
$_POST = []
2021-02-18 10:52:57 [-][-][-][info][postie] FedEx: Sending payload: `{}`.
2021-02-18 10:53:01 [-][-][-][error][postie] FedEx: Rate Error: There are no valid services available. 
2021-02-18 10:53:01 [-][-][-][error][postie] FedEx: Rate Error: The origin state/province code has been changed.  
2021-02-18 10:53:01 [-][-][-][error][postie] FedEx: Rate Error: The destination state/province code has been changed.  
2021-02-18 10:52:57 [-][-][-][info][application] $_GET = [
    'action' => 'commerce/cart/get-cart'
    'note' => 'from ajax'
]

$_POST = []
2021-02-18 10:59:01 [-][-][-][info][postie] FedEx: Sending payload: `{}`.
2021-02-18 10:59:02 [-][-][-][error][postie] FedEx: Rate Error: There are no valid services available. 
2021-02-18 10:59:02 [-][-][-][error][postie] FedEx: Rate Error: The origin state/province code has been changed.  
2021-02-18 10:59:02 [-][-][-][error][postie] FedEx: Rate Error: The destination state/province code has been changed.  
2021-02-18 10:59:01 [-][-][-][info][application] $_GET = [
    'action' => 'commerce/cart/get-cart'
    'note' => 'from ajax'
]

$_POST = []
2021-02-18 11:51:52 [-][1][-][info][postie] FedEx: Sending payload: `{}`.
2021-02-18 11:51:55 [-][1][-][error][postie] FedEx: Rate Error: There are no valid services available. 
2021-02-18 11:51:55 [-][1][-][error][postie] FedEx: Rate Error: The origin state/province code has been changed.  
2021-02-18 11:51:55 [-][1][-][error][postie] FedEx: Rate Error: The destination state/province code has been changed.  
2021-02-18 11:51:52 [-][1][-][info][application] $_GET = []

$_POST = []
2021-02-18 11:51:55 [-][1][-][info][postie] FedEx: Sending payload: `{}`.
2021-02-18 11:51:56 [-][1][-][error][postie] FedEx: Rate Error: There are no valid services available. 
2021-02-18 11:51:56 [-][1][-][error][postie] FedEx: Rate Error: The origin state/province code has been changed.  
2021-02-18 11:51:56 [-][1][-][error][postie] FedEx: Rate Error: The destination state/province code has been changed.  
2021-02-18 11:51:55 [-][1][-][info][application] $_GET = []

$_POST = []
```

This is the link I was using for creating test account: 
https://www.fedex.com/wpor/wpor/editConsult.do

![Screenshot 2021-02-18 at 12 22 54](https://user-images.githubusercontent.com/23526237/108350454-84d58500-71e4-11eb-8a81-1637cd431d01.png)

The destination addresses I'm using is in The Netherlands as well:
![Screenshot 2021-02-18 at 12 29 20](https://user-images.githubusercontent.com/23526237/108350868-088f7180-71e5-11eb-9854-e87655eb044b.png)

Has it something to do with the empty payload it's sending to FedEx?

**Comment by engram-design** [comment]
No need to worry about the empty payload, that's just a logging issue I need to sort.

I'm interested in these lines:

```
2021-02-18 11:51:55 [-][1][-][error][postie] FedEx: Rate Error: The origin state/province code has been changed.  
2021-02-18 11:51:55 [-][1][-][error][postie] FedEx: Rate Error: The destination state/province code has been changed. 
```

I've not seen that before, but that's coming back from FedEx.

**Comment by engram-design** [comment]
I would also double check your details are working via https://www.fedex.com/en-us/online/rating.html

I've just tested with a Netherlands testing account, with origin/destination Netherlands addresses, and seems to be returning rates.

![image](https://user-images.githubusercontent.com/1221575/108356502-538aa280-7240-11eb-8a7c-ccff89dedaef.png)

**Comment by Stalex89** [comment]
Ok, I double checked the ratings on the website, looks like it should work: 

![Screenshot 2021-02-18 at 13 53 14](https://user-images.githubusercontent.com/23526237/108361372-ab9ab800-71f2-11eb-84ac-2208adb12c71.png)

Just in case I also checked if the problem can be because I'm using Nuxt.js or Postman, but I got the same error in the Craft Commerce example checkout as well:

![Screenshot 2021-02-18 at 13 53 55](https://user-images.githubusercontent.com/23526237/108361286-902fad00-71f2-11eb-88b8-68bc59ff71e0.png)

**Comment by Stalex89** [comment]
Ok, I have installed the clear Craft with Craft Commerce and Postie. Still have the same error.

After diving into a code a little bit, i found the following:

1) First error of sending `{}` payload occurs in the /src/base/Provider.php in the line 615
Dumping the Json::encode($payload) as it is in the plugin returns an empty object, while dumping just the $payload returns an RateRequest object:

![Screenshot 2021-02-23 at 12 25 57](https://user-images.githubusercontent.com/23526237/108837610-c4c8ad80-75d2-11eb-95ff-5ac3faa063a2.png)
![Screenshot 2021-02-23 at 12 26 07](https://user-images.githubusercontent.com/23526237/108837618-c6927100-75d2-11eb-9dfd-b6e43cb3aea7.png)
![Screenshot 2021-02-23 at 12 26 28](https://user-images.githubusercontent.com/23526237/108837622-c85c3480-75d2-11eb-9ae9-987cbea9cc6c.png)
![Screenshot 2021-02-23 at 12 26 40](https://user-images.githubusercontent.com/23526237/108837626-ca25f800-75d2-11eb-910c-76803b1f306b.png)

2) In the /jeremy-dunn/php-fedex-api-wrapper/src/FedEx/RateService/Request.php in line 29 the $response is following:
![Screenshot 2021-02-23 at 12 34 37](https://user-images.githubusercontent.com/23526237/108838366-d494c180-75d3-11eb-811e-bb44bf98df8f.png)
![Screenshot 2021-02-23 at 12 34 56](https://user-images.githubusercontent.com/23526237/108838373-d8c0df00-75d3-11eb-9dd1-a3f8e7643b4f.png)

I see the $rateRequest is passing an object:
![Screenshot 2021-02-23 at 12 38 55](https://user-images.githubusercontent.com/23526237/108838613-2d645a00-75d4-11eb-8326-2029cf63dc2d.png)

Also tried to change the shipping/billing address to one you set in the screenshot, nothing changed:

![Screenshot 2021-02-23 at 12 52 41](https://user-images.githubusercontent.com/23526237/108840093-2b02ff80-75d6-11eb-8a55-4b1d8a5304d8.png)

Is it something to be additionally set up in the Fedex account (apart from the sender address) in order for this plugin to work?
Does the test account work with the plugin?
Also does the plugin work on the localhost?

UPD: When looking at the test credentials creation page I've noticed some small note: 
![Screenshot 2021-02-23 at 13 56 36](https://user-images.githubusercontent.com/23526237/108851892-3e699700-75e5-11eb-86b9-1317ea180b73.png)

So I have before I had only 'Netherlands' Intra Country test key, now I laso created 'Global' one,
Still no luck after applying global key in the settings

**Comment by engram-design** [comment]
Hmmm, I wonder if it's something to do with your test credentials, or something I'm not factoring in on my end. I did note the Global vs Netherlands option and I tried both.

All you should need is:
- Store location set
- Products in cart with weight/dimensions
- Valid delivery address

If you can shoot me an email to `web@verbb.io` I'm happy to share my test credentials with you to rule that out.

**Comment by Stalex89** [comment]
@engram-design Thank you for your help, I emailed you from aleks*****12@gmail.com

**Comment by Stalex89** [comment]
Thank you for the keys provided,

Good news, the key for Netherlands works for me:
![Screenshot 2021-02-23 at 23 17 16](https://user-images.githubusercontent.com/23526237/108918327-7991b780-7631-11eb-88e8-a5a09d6bd481.png)

the Global/US key throws an error:
![Screenshot 2021-02-23 at 23 39 44](https://user-images.githubusercontent.com/23526237/108918357-86aea680-7631-11eb-856b-f01499d6b856.png)
