### ISSUE TITLE
`modifyShippingMethods` event appears in docs but isn't actually included in the latest release.

### ISSUE THREAD

**Issue by michaelrog** [verbb/postie#66]
The [docs](https://verbb.io/craft-plugins/postie/docs/developers/events#the-modifyShippingMethods-event) describe a `modifyShippingMethods` event.

Alas, I am unable to find this event implemented anywhere in the code.

...which is super sad, because it's _exactly_ the event I need this morning. 😅 

**Steps to reproduce**
1. Attempt to attach an event listener to the `modifyShippingMethods` event; scratch head when it doesn't work.
2. Ctrl-F in the code, attempting to find where the `modifyShippingMethods` is implemented; scratch head when it cannot be found.

**Additional info**
- Plugin version: 2.4.7

**Comment by michaelrog** [comment]
Ah, I do see where [this event _was_ implemented](https://github.com/michaelrog/postie/commit/41f3273fa98dc1a720b156b0841d25cb6b947be0) in 41f3273... so I guess it just hasn't made it to release yet.

Force-installing the latest files gets me what I need for now...

```
"require": {
    "verbb/postie": "dev-craft-3 as 2.4.7",
},
```

...but I feel kinda dirty pushing this to prod. Hope it gets tagged soon. 🙏🏼

**Comment by engram-design** [comment]
Yep, I was awaiting some feedback for support requests (that've taken a while to get back to me). I'll be sure to tag a release soon!

**Comment by engram-design** [comment]
Added in [2.4.8](https://github.com/verbb/postie/releases/tag/2.4.8)
