### ISSUE TITLE
Add event to modify rate-hydrated Shipping Methods before they get registered

### ISSUE THREAD

**Issue by michaelrog** [verbb/postie#67]
**What are you trying to do?**

I need a way to modify the final collection of Shipping Methods _before_ they get registered with Commerce, but _after_ they have prices assigned.

It looks like the `modifyShippingMethods` event, as currently implemented, only allows me to modify the list of _potential_ shipping methods. This occurs _before_ the list of Shipping Methods is hydrated with price info from the Rates.

My specific use case is: I'm implementing a "Free Shipping" feature, but I only want to apply a discount to the method that would otherwise be least expensive. I need to detect the least expensive Shipping Method and change both its price _and_ its name.

**What's your proposed solution?**

Add a `beforeRegisterShippingMethods` event that lives in `Service::registerShippingMethods()` rather than in an individual provider.

**Comment by engram-design** [comment]
Thanks so much for the [PR](https://github.com/verbb/postie/pull/68). Good point on this, and hadn't really considered that case when needing to compare multiple providers, but makes total sense. I never say no to more events!

**Comment by engram-design** [comment]
Added in [2.4.8](https://github.com/verbb/postie/releases/tag/2.4.8)
