### ISSUE TITLE
Unable to add addition package/box types with l/w/h and weight capacity

### ISSUE THREAD

**Issue by mahajanl** [verbb/postie#73]
**Description**
Hi there, 

I see the ability to add an additional box size to the pre-popuated table of box sizes in the CP. example below:
![image](https://user-images.githubusercontent.com/32281765/126664166-00a9224a-b309-4fcc-90d6-933207593715.png)

**Steps to reproduce**
1. hop into the CP, choose UPS (that's what I'm using)
2. there's a great little table pre-popped, and a not-disabled-looking bar at the bottom to add a row
3. seems clickable - which would be great - but nothing happens and I cannot add in the box sizes my clients use instead of UPS's

**Additional info**
- Plugin version: 2.4.7
- Craft version: 3.5.19.1
- Multi-site: Yes or No - Nope

**Additional context**
Thanks!

**Comment by engram-design** [comment]
So if you click "Add a row" nothing happens? Are there any JS errors?

**Comment by mahajanl** [comment]
Indeed, nothing happened. However - this is a non-issue now - it just took a bit for it to load. I hard refreshed and let the page sit and we're fine. Thanks for the speedy response though!
