### ISSUE TITLE
Handle estimated shipping addresses

### ISSUE THREAD

**Issue by stuart-haas** [verbb/postie#74]
**What are you trying to do?**

Add condition to allow estimated shipping addresses for unauthenticated users.

**What's your proposed solution?**

I had to copy the plugin into the project so it's under our source control now.

Here's the change I'm proposing in `base/Provider.php` on line 394.

```
        if (!$order->shippingAddress && !$order->estimatedShippingAddress) {
            Provider::log($this, 'No shipping address for order.');

            return;
        }
```

**Additional context**

Currently if you try to provide an `estimateShippingAddress` in the `update-cart` action these errors
will be logged in `postie.log`.

```
[-][-][-][info][postie] UPS: No line items for order.
[-][-][-][info][postie] UPS: No line items for order.
[-][-][-][info][postie] UPS: No shipping address for order.
[-][-][-][info][postie] UPS: No shipping address for order.
[-][-][-][info][application] $_GET = []

$_POST = [
    'action' => 'commerce/cart/update-cart'
    'purchasableId' => '59548'
    'qty' => '10'
    'estimatedShippingAddress' => [
        'zipCode' => 'redacted'
    ]
]
```

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/postie` requirement in `composer.json` to:

```
"require": {
  "verbb/postie": "dev-craft-3 as 2.4.8",
  "...": "..."
}
```

Then run `composer update`.

**Comment by joshparylak** [comment]
@engram-design Do you have an idea when the next release is? We'd like to get back on the stable release track when we can.

**Comment by engram-design** [comment]
Was still awaiting some feedback from other support tickets, but tagged a [2.4.9](https://github.com/verbb/postie/releases/tag/2.4.9) release
