### ISSUE TITLE
Ability to use custome packaging on Australia Post

### ISSUE THREAD

**Issue by ax2000** [verbb/postie#76]
My client is sending deliveries using a custom sized box and the price they get from Australia Post when submitting the delivery is higher than the one that Postie receives from the API call, and I think it has to do with the custom size of the box.

Australia Post allows to use your own packaging but it seems to affect the final postage cost as per below:

![Screen Shot 2021-09-13 at 13 29 44](https://user-images.githubusercontent.com/2585959/133019794-b550474a-c095-4b2b-8c94-ab604c02025b.png)
(https://auspost.com.au/sending/check-sending-guidelines/size-weight-guidelines)

I've looked around in the config settings but I couldn't find a way to specify dimensions for a custom box delivery (and I'm also not sure if it's even possible to do through the API).

Could you please let me know if I have missed something or if this would be something for the plugin to handle?

**Additional context**
Screenshot of the Postage calculator tool using custom size box (For the same weight parcel, Postie received a cost of $19.20 for an Express Post parcel)
![Screen Shot 2021-09-13 at 13 34 57](https://user-images.githubusercontent.com/2585959/133020146-e2f0fcd8-1198-4abc-8d92-ba717395c2cc.png)
(https://auspost.com.au/parcels-mail/calculate-postage-delivery-times/#/option/domestic/3000/4217)

Thanks in advance,
Alby.

**Comment by engram-design** [comment]
Are you using the "Pack items into boxes" setting for the provider? With this, you can use the predefined ones from Australia Post, but also provide your own custom boxes. During checkout, Postie will determine (through a box-packing algorithm) the best way to fit items into a box (or multiple boxes).

![image](https://user-images.githubusercontent.com/1221575/133022497-ea366f26-8d85-4973-9cc8-366b4039803a.png)

**Comment by ax2000** [comment]
Thanks for your prompt reply @engram-design - I completely overlooked that option (I had it set to `singleBox` instead of `boxPacking`).

The only thing now, is that when I click on the `Add Row` button on the `Box Sizes` list, nothing seems to happen (no new row is shown or nothing changes). I've checked the console for errors but nothing comes up. Are you able to replicate from your end?

I'm on:
Craft CMS 3.7.4
Postie        2.4.8
PHP           7.3.30

If you can't replicate I'll try and update craft and plugins to the latest versions and see if that's the problem.

Thanks heaps,
Alby.

**Comment by engram-design** [comment]
@ax2000 Yep, it's probably easier to miss if you're configuring things through the config file.

Strange, can't seem to replicate that on my end I'm afraid, but does sound like some sort of JS error. I imagine you see the standard boxes, you just can't add custom ones?

![image](https://user-images.githubusercontent.com/1221575/133517585-b56c39ad-4c05-4133-b665-dd255ed019e6.png)

**Comment by ax2000** [comment]
Thanks for looking at this @engram-design. 

That's right, I see the standard rows but when clicking on `Add Row` nothing happens and no JS error appeared in the console either. 

It seems that is an environment issue from my end so I'm going to update to latest versions and try deactivating some other plugins to see if I can narrow down what the issue could be.

Will keep you posted with what I find out.

**Comment by engram-design** [comment]
Closing due to age.
