### ISSUE TITLE
Australia post API gives API error: “Undefined index: code” after the fix for internatioanl rates

### ISSUE THREAD

**Issue by azad6026** [verbb/postie#80]
**Description**
Hi devs and thanks for considering this.

After updating my site to the latest version of Postie , Craft and Craft commerce , the delivery is not working anymore. Upon logs I can see it is the change that was made on [this commit](https://github.com/verbb/postie/commit/0bb16711b8edabc80b685150380077ed4c410336) based on the logs:

```

$_POST = []
2021-12-10 16:08:42 [-][1][-][info][postie] Australia Post: Domestic API call
2021-12-10 16:08:42 [-][1][-][info][postie] Australia Post: Sending payload: `{"from_postcode":"3121","to_postcode":"3000","length":23,"width":15.5,"height":1.5,"weight":0.4}`.
2021-12-10 16:08:42 [-][1][-][error][postie] Australia Post: API error: “Undefined index: code” /......./vendor/verbb/postie/src/providers/AustraliaPost.php:362
2021-12-10 16:08:41 [-][1][-][info][application] $_GET = [
    'p' => 'shop/checkout/shipping'
    'action' => 'commerce/cart/get-cart'
]
```

Here are the two lines that the change was committed three days ago:

```
        ---> deleted    if (isset($response['services']['service'])) {
        ---> deleted          foreach ($response['services']['service'] as $service) {
        ---> added    if (isset($response['services'])) {
        ---> added        foreach ($response['services'] as $service) {
```
-- | --

I modified the file in the vendor folder and changed it back and all is fine now, but that is not ideal .So if you can have a look and release a fix it will be great as I need it for the live site. 

**Additional info**
- Plugin version: 2.4.13
- Craft version: 3.7.25.1
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Looks like you're right. It seems like for some destinations the data returned is actually different, which was the reason for fixing the error in the first place, as some destination countries weren't returning rates.

Incredibly, AusPost seems to change the result from its API is only a single service was returned, which I'm surprised they do, as it's just inconsistent responses from their system.

Anyway, sorry for the issue, should be properly fixed in [2.4.14](https://github.com/verbb/postie/releases/tag/2.4.14)

**Comment by azad6026** [comment]
Thank you for clarifying. Appreciate it.Is it possible to have an early dev version for the fix  that I can update via composer?

**Comment by engram-design** [comment]
You can update to the latest version 2.4.14 via composer?

**Comment by azad6026** [comment]
Yes I can. Thanks will try it out tonight.
