### ISSUE TITLE
Craft 4 - Calling unknown method: craft\commerce\Plugin::getAddresses()

### ISSUE THREAD

**Issue by seandelaney** [verbb/postie#88]
**Description**

https://github.com/verbb/postie/blob/craft-4/src/controllers/PluginController.php#L63

![Screenshot 2022-03-21 at 15 41 53](https://user-images.githubusercontent.com/580403/159297470-d5fcdbd3-4ad2-46dc-bbb9-debf5ce5426a.png)

**Steps to reproduce**
1. Install 3.0.0-beta.1
2. View Postie Settings

**Additional info**
- Plugin version: 3.0.0-beta.1
- Craft version: 4.0.0-beta.2
- Multi-site: No

**Additional context**
I'm trying to upgrade a Provider plugin for Craft 4 and I'm getting the above error.

Need to use new Store address functions:

https://craftcms.com/docs/commerce/4.x/upgrading.html#store-address

**Comment by engram-design** [comment]
Thanks for this - still trying to work through some Commerce changes that have broken Postie (even with the known changes/updated made), so will update here when those have been sorted on Commerce's end!

**Comment by engram-design** [comment]
Sorted in [3.0.0](https://github.com/verbb/postie/releases/tag/3.0.0)
