### ISSUE TITLE
Config settings not overriding provider values in Craft 4

### ISSUE THREAD

**Issue by johnj24** [verbb/postie#98]
### Describe the bug

Converting a Craft 3/Commerce 3 to Craft 4/Commerce 4 and the Postie config is not being read in the control panel.

My config file is as follows:

```
<?php

return [
  '*' => [
    'hasCpSection' => true,
    'applyFreeShipping' => true,
    'providers' => [
      'usps' => [
        'name' => 'USPS',
        'enabled' => true,
        'settings' => [
          'username' => 'XXXXXXXXXXX',
        ],
        // Mark-Up
        'markUpRate' => '0.50',
        'markUpBase' => 'value',

        // Units
        'weightUnit' => 'lb',
        'dimensionUnit' => 'in',

        // Packing method
        'packingMethod' => 'boxPacking',
      ],
    ],
  ]
];
```

### Steps to reproduce

1. Create config/postie.php
2. Add config options and values
3. Go to CP > Postie > USPS

### Craft CMS version

4.3.4

### Plugin version

3.0.1

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [3.0.2](https://github.com/verbb/postie/releases/tag/3.0.2)
