### ISSUE TITLE
USPS: API error: “Undefined variable $countryIso”

### ISSUE THREAD

**Issue by johnj24** [verbb/postie#99]
### Describe the bug

I'm converting a Craft/Commerce 3 project to Craft/Commerce 4 and upon testing the checkout sequence, I'm getting an error when trying to select a shipping method.

```'USPS: API error: “Undefined variable $countryIso” /Users/.../.../.../.../vendor/verbb/postie/src/providers/USPS.php:195'```

I can confirm that the order has a shipping country applied to it. And we're only using USPS with two services: Priority Mail Medium Flat Rate Box and Media Mail.

### Steps to reproduce

1. Enable USPS
2. Enable Medium Flat Rate Box and Media Mail
3. On the front-end, enter your shipping address, hit submit, and look for a shipping method on the following page.

### Craft CMS version

4.3.4

### Plugin version

3.0.1

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [3.0.2](https://github.com/verbb/postie/releases/tag/3.0.2)
